[package]
name = 'yaml12'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'yaml12'

[dependencies]
extendr-api = '0.8.1'

[profile.release]
lto = true
codegen-units = 1
