[package]
name = 'yaml12'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'yaml12'

[dependencies]
extendr-api = { git = 'https://github.com/extendr/extendr' }
saphyr = "0.0.6"

[profile.release]
lto = true
codegen-units = 1
